# Generated by Django 3.2.9 on 2022-02-01 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_done',
            field=models.BooleanField(default=False),
        ),
    ]
