# Generated by Django 3.2.9 on 2022-04-26 12:43

from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0003_product_search_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataResourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', jsonfield.fields.JSONField()),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parse.product')),
            ],
        ),
    ]
