# Generated by Django 3.2.9 on 2022-05-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0004_dataresourse'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1000)),
                ('url', models.CharField(max_length=1000)),
                ('document', models.ManyToManyField(to='parse.Document')),
            ],
        ),
    ]
