# Generated by Django 3.2.9 on 2022-05-21 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('parse', '0005_auto_20220521_2229'),
    ]

    operations = [
        migrations.AddField(
            model_name='dataresourse',
            name='store',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parse.store'),
        ),
    ]
